import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const roboto = Roboto({
	weight: ["100", "300", "400", "500", "700", "900"],
	subsets: ["latin"],
});

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={roboto.className}>
			<body className={`${roboto.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
